FROM node:16-alpine3.11

# Create app directory
WORKDIR /usr/src/app

COPY . . 

# Install app dependencies
COPY package.json .
COPY yarn.lock .

# in prod we need to build the plugins before running the worker.
RUN yarn && yarn plugins:build